name       = ['Hydrogen', 'Helium', 'Lithium', 'Beryllium', 'Boron', 'Carbon', 'Nitrogen', 'Oxygen', 'Fluorine', 'Neon', 'Sodium', 'Magnesium', 'Aluminium', 'Silicon', 'Phosphorus', 'Sulfur', 'Chlorine', 'Argon', 'Potassium', 'Calcium', 'Scandium', 'Titanium', 'Vanadium', 'Chromium', 'Manganese', 'Iron', 'Cobalt', 'Nickel', 'Copper', 'Zinc', 'Gallium', 'Germanium', 'Arsenic', 'Selenium', 'Bromine', 'Krypton', 'Rubidium', 'Strontium', 'Yttrium', 'Zirconium', 'Niobium', 'Molybdenum', 'Technetium', 'Ruthenium', 'Rhodium', 'Palladium', 'Silver', 'Cadmium', 'Indium', 'Tin', 'Antimony', 'Tellurium', 'Iodine', 'Xenon', 'Cesium', 'Barium', 'Lanthanum', 'Cerium', 'Praseodymium', 'Neodymium', 'Promethium', 'Samarium', 'Europium', 'Gadolinium', 'Terbium', 'Dysprosium', 'Holmium', 'Erbium', 'Thulium', 'Ytterbium', 'Lutetium', 'Hafnium', 'Tantalum', 'Tungsten', 'Rhenium', 'Osmium', 'Iridium', 'Platinum', 'Gold', 'Mercury', 'Thallium', 'Lead', 'Bismuth', 'Polonium', 'Astatine', 'Radon', 'Francium', 'Radium', 'Actinium', 'Thorium', 'Protactinium', 'Uranium', 'Neptunium', 'Plutonium', 'Americium', 'Curium', 'Berkelium', 'Californium', 'Einsteinium', 'Fermium', 'Mendelevium', 'Nobelium', 'Lawrencium', 'Rutherfordium', 'Dubnium', 'Seaborgium', 'Bohrium', 'Hassium', 'Meitnerium', 'Darmstadtium', 'Roentgenium', 'Copernicium', 'Nihonium', 'Flerovium', 'Moscovium', 'Livermorium', 'Tennessine', 'Oganesson', 'Ununennium']
symbol     = ['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne', 'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te', 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn', 'Fr', 'Ra', 'Ac', 'Th', 'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 'Cf', 'Es', 'Fm', 'Md', 'No', 'Lr', 'Rf', 'Db', 'Sg', 'Bh', 'Hs', 'Mt', 'Ds', 'Rg', 'Cn', 'Nh', 'Fl', 'Mc', 'Lv', 'Ts', 'Og', 'Uue']
state      = ['Gas', 'Gas', 'Solid', 'Solid', 'Solid', 'Solid', 'Gas', 'Gas', 'Gas', 'Gas', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Gas', 'Gas', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Liquid', 'Gas', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Gas', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Liquid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Gas', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Liquid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid', 'Solid']
period     = [1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8]
density    = [0.08988, 0.1786, 0.534, 1.85, 2.08, 1.821, 1.251, 1.429, 1.696, 0.9002, 0.968, 1.738, 2.7, 2.329, 1.823, 2.07, 3.2, 1.784, 0.862, 1.55, 2.985, 4.506, 6, 7.19, 7.21, 7.874, 8.9, 8.908, 8.96, 7.14, 5.91, 5.323, 5.727, 4.81, 3.1028, 3.749, 1.532, 2.64, 4.472, 6.52, 8.57, 10.28, 11, 12.45, 12.41, 12.023, 10.49, 8.65, 7.31, 7.365, 6.697, 6.24, 4.933, 5.894, 1.93, 3.51, 6.162, 6.77, 6.77, 7.01, 7.26, 7.52, 5.264, 7.9, 8.23, 8.54, 8.79, 9.066, 9.32, 6.9, 9.841, 13.31, 16.69, 19.25, 21.02, 22.59, 22.56, 21.45, 19.3, 13.534, 11.85, 11.34, 9.78, 9.196, 6.35, 9.73, 1.87, 5.5, 10, 11.724, 15.37, 19.1, 20.45, 19.816, 12, 13.51, 14.78, 15.1, 8.84, None, None, None, None, 23.2, 29.3, 35, 37.1, 40.7, 37.4, 34.8, 28.7, 14.0, 16, 14, 13.5, 12.9, 7.17, 4.95, 3]
appearance = ['colorless gas', 'colorless gas, exhibiting a red-orange glow when placed in a high-voltage electric field', 'silvery-white', 'white-gray metallic', 'black-brown', None, 'colorless gas, liquid or solid', None, None, 'colorless gas exhibiting an orange-red glow when placed in a high voltage electric field', 'silvery white metallic', 'shiny grey solid', 'silvery gray metallic', 'crystalline, reflective with bluish-tinged faces', 'colourless, waxy white, yellow, scarlet, red, violet, black', 'lemon yellow sintered microcrystals', 'pale yellow-green gas', 'colorless gas exhibiting a lilac/violet glow when placed in a high voltage electric field', 'silvery gray', None, 'silvery white', 'silvery grey-white metallic', 'blue-silver-grey metal', 'silvery metallic', 'silvery metallic', 'lustrous metallic with a grayish tinge', 'hard lustrous gray metal', 'lustrous, metallic, and silver with a gold tinge', 'red-orange metallic luster', 'silver-gray', 'silver-white', 'grayish-white', 'metallic grey', 'black, red, and gray (not pictured) allotropes', None, 'colorless gas, exhibiting a whitish glow in a high electric field', 'grey white', None, 'silvery white', 'silvery white', 'gray metallic, bluish when oxidized', 'gray metallic', 'shiny gray metal', 'silvery white metallic', 'silvery white metallic', 'silvery white', 'lustrous white metal', 'silvery bluish-gray metallic', 'silvery lustrous gray', 'silvery-white (beta, β) or gray (alpha, α)', 'silvery lustrous gray', None, 'lustrous metallic gray, violet as a gas', 'colorless gas, exhibiting a blue glow when placed in a high voltage electric field', 'silvery gold', None, 'silvery white', 'silvery white', 'grayish white', 'silvery white', 'metallic', 'silvery white', None, 'silvery white', 'silvery white', 'silvery white', 'silvery white', 'silvery white', 'silvery gray', None, 'silvery white', 'steel gray', 'gray blue', 'grayish white, lustrous', 'silvery-grayish', 'silvery, blue cast', 'silvery white', 'silvery white', 'metallic yellow', 'silvery', 'silvery white', 'metallic gray', 'lustrous silver', 'silvery', 'unknown, probably metallic', 'colorless gas, occasionally glows green or red in discharge tubes', None, 'silvery white metallic', None, 'silvery, often with black tarnish', 'bright, silvery metallic luster', None, 'silvery metallic', 'silvery white, tarnishing to dark gray in air', 'silvery white', 'silvery metallic, glows purple in the dark', 'silvery', 'silvery', 'silver-colored', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
element    = [None]*len(name)
elementin  = ["name ", "symbol", "state ", "period ", "density ", "appearance "]
for i in range(0,len(appearance)):
    element[i] = name[i] + "," + symbol[i] + "," + state[i] + "," + str(period[i]) + "," + str(density[i]) + "," + str(appearance[i])

question = input("Which element would you like to know about?")
for j in range(0,len(appearance)):
    if question.lower() == name[j].lower() or question.lower() == symbol[j].lower():
        print("This will show as name,symbol,state,period,density,appearance")
        print(element[j])